import React from 'react';

const Privacy: React.FC = () => {
  return (
    <div className="py-16">
      <div className="container">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl font-bold mb-8">Find My Things Privacy Policy</h1>
          <p className="text-gray-600 mb-8">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
          
          <div className="prose prose-lg max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Introduction</h2>
              <p>
                Find My Things ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and share information about you when you use our website and mobile application Find My Things (the "App" and "Website").
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Information We Collect</h2>

              <h3 className="text-xl font-medium mb-2">Information You Provide</h3>
              <ul className="list-disc pl-5 mb-4">
                <li>Personal information such as name and email address</li>
                <li>Subscription and payment information (processed securely by Apple)</li>
              </ul>

              <h3 className="text-xl font-medium mb-2">Information Collected Automatically</h3>
              <ul className="list-disc pl-5">
                <li>Device information (model, operating system)</li>
                <li>App usage statistics and analytics</li>
                <li>Error logs and performance data</li>
                <li>Website usage data through cookies and similar technologies</li>
              </ul>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Cookies and Similar Technologies</h2>
              <p>
                Our website uses cookies and similar tracking technologies to collect information about your browsing activities. Cookies are small text files that are stored on your device when you visit our website.
              </p>
              
              <h3 className="text-xl font-medium mb-2 mt-4">Types of Cookies We Use</h3>
              <ul className="list-disc pl-5">
                <li><strong>Strictly Necessary Cookies:</strong> These cookies are essential for the website to function properly and cannot be turned off in our systems.</li>
                <li><strong>Analytics/Performance Cookies:</strong> These cookies allow us to recognize and count the number of visitors and to see how visitors move around our website. This helps us to improve the way our website works. We use Google Analytics for this purpose.</li>
              </ul>
              
              <h3 className="text-xl font-medium mb-2 mt-4">Google Analytics</h3>
              <p>
                We use Google Analytics, a web analytics service provided by Google LLC ("Google"). Google Analytics uses cookies to help us analyze how users use our website. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States.
              </p>
              <p className="mt-2">
                Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for us, and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf.
              </p>
              <p className="mt-2">
                You can prevent Google's collection and use of data by downloading and installing the browser plugin available at: <a href="https://tools.google.com/dlpage/gaoptout" className="text-blue-600 hover:underline">https://tools.google.com/dlpage/gaoptout</a>.
              </p>
              
              <h3 className="text-xl font-medium mb-2 mt-4">Your Cookie Choices</h3>
              <p>
                When you first visit our website, you will be presented with a cookie consent banner that allows you to accept or decline the use of analytics cookies. You can change your cookie preferences at any time by clearing your browser cookies and reloading the website.
              </p>
              <p className="mt-2">
                Most web browsers allow you to control cookies through their settings preferences. To find out more about cookies, including how to see what cookies have been set and how to manage and delete them, visit <a href="https://www.allaboutcookies.org" className="text-blue-600 hover:underline">www.allaboutcookies.org</a>.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">How We Use Your Information</h2>
              <p>We use your information to:</p>
              <ul className="list-disc pl-5">
                <li>Provide, maintain, and improve the App and Website</li>
                <li>Process transactions and manage your account</li>
                <li>Respond to your comments and questions</li>
                <li>Send you technical notices and updates</li>
                <li>Analyze usage patterns to enhance user experience</li>
                <li>Measure the effectiveness of our marketing campaigns</li>
                <li>Detect, prevent, and address technical issues</li>
              </ul>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Data Storage and Security</h2>
              
              <h3 className="text-xl font-medium mb-2">Local Data Storage</h3>
              <p className="mb-4">
                Your inventory data (items, categories, locations, collections, and photos) is stored locally on your device using secure iOS storage mechanisms. This includes:
              </p>
              <ul className="list-disc pl-5 mb-4">
                <li>Item details, descriptions, and metadata</li>
                <li>Optimized photos (automatically compressed to save space)</li>
                <li>Custom categories, locations, and tags</li>
                <li>Borrowing history and reminder settings</li>
                <li>Collections and organizational preferences</li>
              </ul>
              
              <h3 className="text-xl font-medium mb-2">iCloud Backup (Optional)</h3>
              <p className="mb-4">
                If you have enabled iCloud Backup on your device, your FindMyThings data may be included in your device's automatic iCloud backup. This is controlled entirely by your device settings, not by our app:
              </p>
              <ul className="list-disc pl-5 mb-4">
                <li><strong>User Control:</strong> You can enable or disable iCloud backup for FindMyThings in your device's Settings &gt; [Your Name] &gt; iCloud &gt; iCloud Backup</li>
                <li><strong>Apple's Responsibility:</strong> iCloud backup and restoration are handled entirely by Apple's iCloud service</li>
                <li><strong>Data Protection:</strong> iCloud backups are encrypted and protected by your Apple ID credentials</li>
                <li><strong>Restoration:</strong> When restoring from an iCloud backup, your FindMyThings data will be restored automatically if previously backed up</li>
              </ul>
              
              <h3 className="text-xl font-medium mb-2">Security Measures</h3>
              <p>
                We implement appropriate technical and organizational measures to protect your personal information, including secure local storage and adherence to iOS security best practices. However, no system is 100% secure, and we cannot guarantee absolute security of your data.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Subscription Information</h2>
              <p>
                Subscription payments are processed by Apple. We do not store your payment information. For information about how Apple handles your payment data, please refer to Apple's Privacy Policy.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Information Sharing and Third-Party Services</h2>
              
              <h3 className="text-xl font-medium mb-2">When We Share Your Information</h3>
              <p className="mb-4">
                We may share your personal information in the following circumstances:
              </p>
              
              <h4 className="text-lg font-medium mb-2">Service Providers</h4>
              <p className="mb-2">We may share information with third-party service providers who assist us in operating our app and website:</p>
              <ul className="list-disc pl-5 mb-4">
                <li><strong>Analytics Providers:</strong> Google Analytics to analyze website traffic and usage patterns</li>
                <li><strong>Marketing Tools:</strong> Google Tag Manager to manage and deploy marketing tags</li>
                <li><strong>Performance Monitoring:</strong> Analytics tools to improve app performance and identify issues</li>
                <li><strong>Error Reporting:</strong> Crash reporting services to identify and fix bugs</li>
                <li><strong>App Store Services:</strong> Apple for subscription processing and app distribution</li>
              </ul>
              
              <h4 className="text-lg font-medium mb-2">Business Partners</h4>
              <p className="mb-4">
                We do not currently share personal information with business partners for marketing purposes. If this changes, we will update this policy and notify you.
              </p>
              
              <h4 className="text-lg font-medium mb-2">Legal Requirements</h4>
              <p className="mb-2">We may disclose your information when required by law or to:</p>
              <ul className="list-disc pl-5 mb-4">
                <li>Comply with legal processes, court orders, or government requests</li>
                <li>Enforce our Terms of Service or other agreements</li>
                <li>Protect our rights, property, or safety, or that of our users</li>
                <li>Investigate suspected fraud, security breaches, or other violations</li>
                <li>Comply with applicable data protection and privacy laws</li>
              </ul>
              
              <h4 className="text-lg font-medium mb-2">Business Transfers</h4>
              <p className="mb-4">
                In the event of a merger, acquisition, sale of assets, or bankruptcy, your personal information may be transferred to the acquiring entity. We will provide notice before your information is transferred and becomes subject to a different privacy policy.
              </p>
              
              <h4 className="text-lg font-medium mb-2">Affiliates</h4>
              <p className="mb-4">
                We may share information with our affiliates, subsidiaries, or parent companies, if any, for business purposes. All such entities will be required to use your information in accordance with this Privacy Policy.
              </p>
              
              <h3 className="text-xl font-medium mb-2">Third-Party Privacy Policies</h3>
              <p>
                These third-party services have their own privacy policies. We encourage you to review them:
              </p>
              <ul className="list-disc pl-5 mb-4">
                <li><strong>Google Analytics:</strong> <a href="https://policies.google.com/privacy" className="text-blue-600 hover:underline">Google Privacy Policy</a></li>
                <li><strong>Apple App Store:</strong> <a href="https://www.apple.com/privacy/" className="text-blue-600 hover:underline">Apple Privacy Policy</a></li>
              </ul>
              
              <p>
                We are not responsible for the privacy practices of these third parties and recommend that you carefully review their privacy policies.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">International Data Transfers</h2>
              <p className="mb-4">
                Your information may be transferred to, stored, and processed in countries other than your country of residence, including the United States and other countries where our service providers operate.
              </p>
              
              <h3 className="text-xl font-medium mb-2">Cross-Border Processing</h3>
              <p className="mb-4">
                When we transfer your personal information internationally, we implement appropriate safeguards to protect your data:
              </p>
              <ul className="list-disc pl-5 mb-4">
                <li><strong>Adequacy Decisions:</strong> We transfer data to countries that have been deemed to provide adequate protection by relevant authorities</li>
                <li><strong>Standard Contractual Clauses:</strong> We use European Commission-approved standard contractual clauses for transfers to countries without adequacy decisions</li>
                <li><strong>Certification Programs:</strong> We work with service providers who participate in recognized certification frameworks</li>
                <li><strong>Technical Safeguards:</strong> All data transfers are protected by encryption and other technical measures</li>
              </ul>
              
              <h3 className="text-xl font-medium mb-2">Your Rights Regarding International Transfers</h3>
              <p className="mb-4">
                If you are located in the European Economic Area (EEA), UK, or Switzerland, you have the right to request information about the safeguards we have in place for international transfers of your personal data. You may contact us using the information provided in the "Contact Us" section.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Children's Privacy</h2>
              <p className="mb-4">
                The App is not directed to children under 13, and we do not knowingly collect personal information from children under 13. If you are between 13 and 18 years of age, you may only use the App with parental or guardian consent.
              </p>
              <p>
                If we become aware that we have collected personal information from a child under 13 without parental consent, we will take steps to delete that information as quickly as possible. If you believe we may have collected information from a child under 13, please contact us immediately at sachtech.com.apps@gmail.com.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Changes to This Privacy Policy</h2>
              <p>
                We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Your Privacy Rights</h2>
              <p className="mb-4">
                Depending on your location and applicable laws, you may have certain rights regarding your personal information:
              </p>
              
              <h3 className="text-xl font-medium mb-2">General Privacy Rights</h3>
              <ul className="list-disc pl-5 mb-4">
                <li><strong>Right to Access:</strong> Request a copy of the personal information we hold about you</li>
                <li><strong>Right to Rectification:</strong> Request correction of inaccurate or incomplete information</li>
                <li><strong>Right to Erasure:</strong> Request deletion of your personal data under certain circumstances</li>
                <li><strong>Right to Restrict Processing:</strong> Request that we limit how we use your information</li>
                <li><strong>Right to Object:</strong> Object to our processing of your information for certain purposes</li>
                <li><strong>Right to Withdraw Consent:</strong> Withdraw consent at any time where processing is based on consent</li>
              </ul>
              
              <h3 className="text-xl font-medium mb-2">Data Portability</h3>
              <p className="mb-4">
                You have the right to receive your personal data in a structured, commonly used format and to transmit that data to another controller. We provide data export functionality within the App to facilitate this right.
              </p>
              
              <h3 className="text-xl font-medium mb-2">Marketing and Communications</h3>
              <p className="mb-4">
                You can opt-out of marketing communications at any time by:
              </p>
              <ul className="list-disc pl-5 mb-4">
                <li>Following the unsubscribe instructions in any marketing email</li>
                <li>Contacting us directly using the information in the "Contact Us" section</li>
                <li>Adjusting your notification preferences in the App settings</li>
              </ul>
              
              <h3 className="text-xl font-medium mb-2">Regional Rights</h3>
              <p className="mb-2"><strong>European Union/EEA Users:</strong></p>
              <ul className="list-disc pl-5 mb-4">
                <li>All rights listed above under GDPR</li>
                <li>Right to lodge a complaint with your local data protection authority</li>
                <li>Right to request details about international data transfers</li>
              </ul>
              
              <p className="mb-2"><strong>California Residents (CCPA):</strong></p>
              <ul className="list-disc pl-5 mb-4">
                <li>Right to know what personal information is collected</li>
                <li>Right to delete personal information</li>
                <li>Right to opt-out of the sale of personal information (we do not sell personal information)</li>
                <li>Right to non-discrimination for exercising CCPA rights</li>
              </ul>
              
              <h3 className="text-xl font-medium mb-2">How to Exercise Your Rights</h3>
              <p className="mb-4">
                To exercise any of these rights, please contact us at sachtech.com.apps@gmail.com with your request. We will respond within the timeframes required by applicable law (typically 30 days).
              </p>
              
              <p>
                <strong>Verification:</strong> To protect your privacy, we may need to verify your identity before processing your request. We may also charge a reasonable fee for excessive or repetitive requests.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
              <p>
                If you have any questions about this Privacy Policy, please contact us at:
              </p>
              <p className="font-medium mt-2">
                sachtech.com.apps@gmail.com
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Privacy; 