import React from 'react';

const Privacy: React.FC = () => {
  return (
    <div className="py-16">
      <div className="container">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl font-bold mb-8">Find My Things Privacy Policy</h1>
          <p className="text-gray-600 mb-8">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
          
          <div className="prose prose-lg max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Introduction</h2>
              <p>
                Find My Things ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and share information about you when you use our website and mobile application Find My Things (the "App" and "Website").
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Information We Collect</h2>

              <h3 className="text-xl font-medium mb-2">Information You Provide</h3>
              <ul className="list-disc pl-5 mb-4">
                <li>Personal information such as name and email address</li>
                <li>Subscription and payment information (processed securely by Apple)</li>
              </ul>

              <h3 className="text-xl font-medium mb-2">Information Collected Automatically</h3>
              <ul className="list-disc pl-5">
                <li>Device information (model, operating system)</li>
                <li>App usage statistics and analytics</li>
                <li>Error logs and performance data</li>
                <li>Website usage data through cookies and similar technologies</li>
              </ul>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Cookies and Similar Technologies</h2>
              <p>
                Our website uses cookies and similar tracking technologies to collect information about your browsing activities. Cookies are small text files that are stored on your device when you visit our website.
              </p>
              
              <h3 className="text-xl font-medium mb-2 mt-4">Types of Cookies We Use</h3>
              <ul className="list-disc pl-5">
                <li><strong>Strictly Necessary Cookies:</strong> These cookies are essential for the website to function properly and cannot be turned off in our systems.</li>
                <li><strong>Analytics/Performance Cookies:</strong> These cookies allow us to recognize and count the number of visitors and to see how visitors move around our website. This helps us to improve the way our website works. We use Google Analytics for this purpose.</li>
              </ul>
              
              <h3 className="text-xl font-medium mb-2 mt-4">Google Analytics</h3>
              <p>
                We use Google Analytics, a web analytics service provided by Google LLC ("Google"). Google Analytics uses cookies to help us analyze how users use our website. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States.
              </p>
              <p className="mt-2">
                Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for us, and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf.
              </p>
              <p className="mt-2">
                You can prevent Google's collection and use of data by downloading and installing the browser plugin available at: <a href="https://tools.google.com/dlpage/gaoptout" className="text-blue-600 hover:underline">https://tools.google.com/dlpage/gaoptout</a>.
              </p>
              
              <h3 className="text-xl font-medium mb-2 mt-4">Your Cookie Choices</h3>
              <p>
                When you first visit our website, you will be presented with a cookie consent banner that allows you to accept or decline the use of analytics cookies. You can change your cookie preferences at any time by clearing your browser cookies and reloading the website.
              </p>
              <p className="mt-2">
                Most web browsers allow you to control cookies through their settings preferences. To find out more about cookies, including how to see what cookies have been set and how to manage and delete them, visit <a href="https://www.allaboutcookies.org" className="text-blue-600 hover:underline">www.allaboutcookies.org</a>.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">How We Use Your Information</h2>
              <p>We use your information to:</p>
              <ul className="list-disc pl-5">
                <li>Provide, maintain, and improve the App and Website</li>
                <li>Process transactions and manage your account</li>
                <li>Respond to your comments and questions</li>
                <li>Send you technical notices and updates</li>
                <li>Analyze usage patterns to enhance user experience</li>
                <li>Measure the effectiveness of our marketing campaigns</li>
                <li>Detect, prevent, and address technical issues</li>
              </ul>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Data Storage and Security</h2>
              <p>
                All your inventory data is stored locally on your device and optionally backed up using your iCloud account. We implement appropriate technical and organizational measures to protect your personal information.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Subscription Information</h2>
              <p>
                Subscription payments are processed by Apple. We do not store your payment information. For information about how Apple handles your payment data, please refer to Apple's Privacy Policy.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Third-Party Services</h2>
              <p>Our app and website may use third-party services that collect information. These services include:</p>
              <ul className="list-disc pl-5">
                <li>Google Analytics to analyze website traffic and usage</li>
                <li>Google Tag Manager to manage and deploy marketing tags</li>
                <li>Analytics tools to improve app performance</li>
                <li>Error reporting tools to identify and fix bugs</li>
              </ul>
              <p className="mt-2">
                These third-party services may use cookies and similar technologies to collect information about your use of our website and app. Please refer to their respective privacy policies for more information on how they process your data.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Children's Privacy</h2>
              <p>
                The App is not directed to children under 13, and we do not knowingly collect personal information from children under 13.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Changes to This Privacy Policy</h2>
              <p>
                We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Your Privacy Rights</h2>
              <p>
                Depending on your location, you may have certain rights regarding your personal information, such as:
              </p>
              <ul className="list-disc pl-5">
                <li>The right to access your personal information</li>
                <li>The right to correct inaccurate information</li>
                <li>The right to request deletion of your data</li>
                <li>The right to opt-out of certain data uses</li>
                <li>The right to withdraw consent at any time</li>
              </ul>
              <p className="mt-2">
                To exercise any of these rights, please contact us using the information provided in the "Contact Us" section.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
              <p>
                If you have any questions about this Privacy Policy, please contact us at:
              </p>
              <p className="font-medium mt-2">
                sachtech.com.apps@gmail.com
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Privacy; 